### ISSUE TITLE
Serverless Cognito support

### ISSUE THREAD

**Issue by dgiebert** [mkotsur/aws-lambda-scala#24]
Trying to enable AWS Cognito results in the following error:

```
Attempt to decode value on failed cursor: DownField(principalId),DownField(authorizer),DownField(requestContext)
```

This is done with the following snippet
```yaml
authorizer:
  name: authorizer
  arn: arn:aws:cognito-idp:us-east-1:123456789:userpool/us-east-1_XXXXXX
```

From what I can undestand it tries to get a `principalId` under `authorizer` but it does not exist and its not an optional:
https://github.com/mkotsur/aws-lambda-scala/blob/master/src/main/scala/io/github/mkotsur/aws/proxy/package.scala#L5

The json looks in a test nodejs hello world like this (removed private data):
```json
"requestContext": {
    "authorizer": {
        "claims": {
            "token_use": "id",
            "auth_time": "1609775553",
            "exp": "Mon Jan 04 16:52:33 UTC 2021",
            "iat": "Mon Jan 04 15:52:33 UTC 2021",
        }
    }
```
