### ISSUE TITLE
How to package?

### ISSUE THREAD

**Issue by hderms** [mkotsur/aws-lambda-scala#7]
do you use sbt-assembly? Anything special that needs to be done? I tried using sbt-assembly but I'm getting: 
```{
  "errorMessage": "Error loading class monitoring.enqueuer.EnqueuerMonitoringLambda: io/github/mkotsur/aws/handler/Lambda",
  "errorType": "java.lang.NoClassDefFoundError"
}
```

**Comment by rmmeans** [comment]
I use sbt-assembly and have no problems with creating lambdas with this. What versions are you using? I'm using scala `2.12.4`, `1.0.5` of this library, SBT `1.0.3` and sbt-assembly `0.14.6`

My SAM stack for my code URI looks something like this:

```yaml
Resources:
  WSBToRedirector:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.lifeway.serverless.appname.Handler::handle
      CodeUri: ./target/scala-2.12/{appname}-assembly-1.0.jar

```

Where the handler Code URI reflects a Scala class that extends this library's Lambda class (my class is called Handler) and the handle method refers to the overridden method from this library.
